networks:
  student_portal_network:
    # network created in Makefile using 'docker network create'
    external: true

services:

  librarydb:
    image: mariadb
    container_name: library_service_db
    restart: always
    volumes:
        - ./migrations/mysql-migrations.sql:/docker-entrypoint-initdb.d/mysql-migrations.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_APPLICATION_USER}
      MYSQL_PASSWORD: ${DB_APPLICATION_PASSWORD}
    command: --innodb-flush-method=fsync --innodb-use-native-aio=0
    networks:
      - student_portal_network
    healthcheck:
      test: "/usr/bin/mariadb --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      timeout: 2s
      retries: 10
    ports:
      - "3309:3306"
    expose:
      - "3309"


  libraryapp:
    image: ces-books:4.0
    container_name: library_service
    environment:
      DATABASE: mysql://${DB_APPLICATION_USER}:${DB_APPLICATION_PASSWORD}@librarydb:3306/${DB_NAME}
    ports:
      - "8082:80"
    expose:
      - "8082"
    depends_on:
      librarydb:
        condition: service_healthy
    networks:
      - student_portal_network
