services:
  student_service_db:
    image: 'postgres:latest'
    container_name: student_service_db
    restart: always
    environment:
      POSTGRES_DB: ${STUDENT_DB_NAME}
      POSTGRES_USER: ${STUDENT_DB_USER}
      POSTGRES_PASSWORD: ${STUDENT_DB_PASS}
    ports:
      - '5432:5432'

  student_service:
    build: .
    container_name: student_service
    environment:
      spring.datasource.url: jdbc:postgresql://student_service_db:5432/${STUDENT_DB_NAME}
      spring.datasource.username: ${STUDENT_DB_USER}
      spring.datasource.password: ${STUDENT_DB_PASS}
    depends_on:
      - student_service_db
    ports:
      - "8080:8080"
