networks:
  student_portal_network:
    # network created in Makefile using 'docker network create'
    external: true

services:
  student-service-db:
    image: 'postgres:latest'
    container_name: student-service-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${STUDENT_DB_NAME}
      POSTGRES_USER: ${STUDENT_DB_USER}
      POSTGRES_PASSWORD: ${STUDENT_DB_PASS}
    networks:
      - student_portal_network
    healthcheck:
      test: "psql -U $$POSTGRES_USER $$POSTGRES_DB"
      timeout: 2s
      retries: 10

  student-service:
    image: 'student-service-image:latest'
    container_name: student-service
    environment:
      spring.datasource.url: jdbc:postgresql://student-service-db:5432/${STUDENT_DB_NAME}
      spring.datasource.username: ${STUDENT_DB_USER}
      spring.datasource.password: ${STUDENT_DB_PASS}
    depends_on:
      student-service-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - student_portal_network
